# Generated by Django 4.1.7 on 2023-05-24 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafileupload',
            name='description',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
